# Generated by Django 6.0 on 2026-02-10 16:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='YogaCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='YogaVinyasa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='YogaPose',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True)),
                ('benefits', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='yoga_poses/')),
                ('procedure', models.TextField(blank=True)),
                ('precautions', models.TextField(blank=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='poses', to='yoga.yogacategory')),
            ],
            options={
                'ordering': ['name'],
                'unique_together': {('category', 'name')},
            },
        ),
        migrations.CreateModel(
            name='YogaVinyasaStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0)),
                ('hold_seconds', models.PositiveIntegerField(default=0)),
                ('notes', models.TextField(blank=True)),
                ('pose', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='yoga.yogapose')),
                ('vinyasa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='yoga.yogavinyasa')),
            ],
            options={
                'ordering': ['order'],
                'unique_together': {('vinyasa', 'order')},
            },
        ),
    ]
