# Generated by Django 6.0 on 2026-02-11 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yoga', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='yogapose',
            name='cimage',
            field=models.ImageField(blank=True, null=True, upload_to='child/'),
        ),
        migrations.AddField(
            model_name='yogapose',
            name='maturity',
            field=models.CharField(choices=[('A', 'Adult'), ('C', 'Child')], default='A', max_length=1),
        ),
    ]
