# Generated by Django 6.0 on 2026-02-12 09:58

import django.db.models.deletion
import yoga.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yoga', '0002_yogapose_cimage_yogapose_maturity'),
    ]

    operations = [
        migrations.CreateModel(
            name='YogaClient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_code', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('address', models.TextField(blank=True)),
                ('contact_no', models.CharField(max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('amount_paid', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('client_status', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive')], default='ACTIVE', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='YogaAdvertisement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True)),
                ('image', models.FileField(upload_to='advertisements/', validators=[yoga.models.validate_ad_file])),
                ('display_seconds', models.PositiveIntegerField(default=30)),
                ('priority', models.PositiveIntegerField(default=1)),
                ('active_from', models.DateField()),
                ('active_to', models.DateField()),
                ('date_disabled', models.DateField(blank=True, null=True)),
                ('disable_reason', models.TextField(blank=True)),
                ('amount_received', models.DecimalField(decimal_places=2, max_digits=10)),
                ('amtrec_date', models.DateField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='advertisements', to='yoga.yogaclient')),
            ],
            options={
                'db_table': 'yoga_advertisements',
                'ordering': ['priority', '-active_from'],
            },
        ),
    ]
